### ISSUE TITLE
test_writer.test_run fails after pulling the 1.9.74.123 release

### ISSUE THREAD

**Issue by vladisld** [backtrader2/backtrader#5]
```
ERROR: test_writer.test_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/backtrader2/backtrader/tests/test_writer.py", line 48, in test_run
    writer=(bt.WriterStringIO, dict(csv=True)))
  File "/home/travis/build/backtrader2/backtrader/tests/testcommon.py", line 110, in runtest
    cerebro.run()
  File "/home/travis/build/backtrader2/backtrader/backtrader/cerebro.py", line 1085, in run
    wr = wrcls(*wrargs, **wrkwargs)
  File "/home/travis/build/backtrader2/backtrader/backtrader/metabase.py", line 88, in __call__
    _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
  File "/home/travis/build/backtrader2/backtrader/backtrader/metabase.py", line 78, in doinit
    _obj.__init__(*args, **kwargs)
  File "/home/travis/build/backtrader2/backtrader/backtrader/writer.py", line 218, in __init__
    self.out = self.out()
AttributeError: 'WriterStringIO' object has no attribute 'out'
----------------------------------------------------------------------
```

Caused by the 71b1781d143d3a74bd1b65d65e54f180c03b9c21.
